---
deployment:
  tasks:
    - export DEPLOYPATH=~/public_html
    - /bin/rm -rd $DEPLOYPATH/*
    - /bin/rm -f $DEPLOYPATH/*.php
    - /bin/cp -R num $DEPLOYPATH
    - /bin/cp -R vegur $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
